FROM semitechnologies/weaviate:latest

ENV QUERY_DEFAULTS_LIMIT=20
ENV AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
ENV PERSISTENCE_DATA_PATH=/var/lib/weaviate
ENV DEFAULT_VECTORIZER_MODULE=text2vec-palm
ENV ENABLE_MODULES=text2vec-palm
ENV CLUSTER_HOSTNAME=node1

VOLUME /var/lib/weaviate

EXPOSE 8080 50051
